server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/community?characterEncoding=UTF-8&serverTimezone=UTC
    username: jaesay
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  data:
    rest:
      base-path: /api
      default-page-size: 10
      max-page-size: 10
  jpa:
    show-sql: true
    generate-ddl: true
  properties:
    hibernate:
      format_sql: true
      ddl-auto: create