server:
  port: 8083
spring:
  datasource:
    url: ENC(Zm2WEzzK5CkCupbogXW+GyRN8XBqosw5wx/EILkW2SXd88KTBNOJfZ3ONFtkB7AjrIZA43GQRtsQFa4bdOfXGMMygie73Gf2FhbkN7IZq97UUF+fX6QlpTh64+FVMe6z)
    username: ENC(4m3O9gel2uMWJutl+BVtFA==)
    password: ENC(n9x6LsBTveowd96Tj0tuqnfo0zWECbu4)
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  devtools:
    livereload:
      enabled: true
  thymeleaf:
      cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 737241285783-tr503pll2uo52i8rq77ta4sdfuinkudc.apps.googleusercontent.com
            client-secret: PTCC39Z68ARGwGJ7PaUup99a
          facebook:
            client-id: 366166617493455
            client-secret: 6c40d973366bc76a7ee688ecc5cfa0d1
      
jasypt:
  encryptor:
    password: MY_PASS
    
logging:
  level:
    org.hibernate: info
    org.springframework.web: debug
    org.springframework.security: debug