spring:
  profiles:
    include:
      - core

server:
  port: 9090
  servlet:
    session:
      cookie:
        name: CMS_SESSIONID
      tracking-modes: cookie

cloud:
  aws:
    s3:
      bucket: toyproject-ecommerce-images
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
