spring:
#  datasource:
#    username: jaesay
#    password: 1234
#    url: jdbc:mysql://127.0.0.1:3306/jojoldu?characterEncoding=UTF-8&serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      .hibernate:
        show_sql: true
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

  h2:
    console:
      enabled: true