server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/community?characterEncoding=UTF-8&serverTimezone=UTC
    username: jaesay
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
  properties:
    hibernate:
      format_sql: true
      ddl-auto: create
  h2:
    console:
      enabled: false
  thymeleaf:
    cache: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
      type:
        descriptor:
          :sql: trace
      :springframework:
        web: debug
        security: debug

devtools:
  livereload:
    enabled: true