spring:
  application:
    name: currency-exchange
  jpa:
    show-sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
  h2:
    console:
      enabled: true
  cloud:
    config:
      enabled: false

server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka