server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/jaeseong/IdeaProjects/native-file-repo
#  cloud:
#    config:
#      server:
#        git:
#          uri: file:///Users/jaeseong/IdeaProjects/git-local-repo
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh
